### PR TITLE
Layout of thank you screen fixed

### LINKED ISSUE #153: Change layout of thank you screen
**Describe the feature you'd like to see included in Planet Pay.**

Screen Shot 2021-10-29 at 12 11 50 PM

### PR DESCRIPTION
**Pull request by rishsingh07**
Fixes #153

- [x] Centered
- [x] Moved

### CODE REVIEW

**Comment by norbertschuler** [comment]
New layout on small screen showing thank you card first - @sagararyal is this how you wanted it?

IMG_ECF4F290C748-1

**Review by sagararyal — CHANGES_REQUESTED** [review]
My suggestion was to take the `Ref-don_xyz` below the cards. Not the whole section.

**Review by sagararyal — CHANGES_REQUESTED** [review]
This PR doesn't yet solve the issue

breaks min height of the cards when content is loading in the payment pages.

eg:
Screen Shot 2021-11-19 at 1 56 27 PM

Screen Shot 2021-11-19 at 1 55 10 PM

Screen Shot 2021-11-19 at 1 56 45 PM

**Comment by sarveshpro** [comment]
Not sure if this is solved yet 
image

**Comment by tejassonar** [comment]
> Not sure if this is solved yet image

It worked for me though. 'ref' should be at the bottom only for the ThankYou screen.

**Review by norbertschuler — APPROVED** [review]
Seems to work:

Bildschirmfoto 2021-11-26 um 18 54 20

**Review by tejassonar — APPROVED** [review]

**Comment by sagararyal** [comment]
Can you please fix the cypress tests?

**Review by sagararyal — APPROVED** [review]

**Pull request merged**
