### PR TITLE
add scrollbar to donation forms

### PR DESCRIPTION
**Pull request by prachigarg19**
Fixes #

https://github.com/Plant-for-the-Planet-org/planet-donations/issues/315

Changes in this pull request:
- added scroll bar to donation forms.

### CODE REVIEW

**Comment by mariahosfeld** [comment]
Please make sure that the scroll bar is only there if searching for a project has more than 8 results. All other styling, especially the donation part should stay the same and be without scrollbars.

**Comment by mariahosfeld** [comment]
General functionality works for me.
Please check how to integrate the scrollbar into our layout, more in terms of how it looks like when you check it on a mobile phone.

**Comment by mariahosfeld** [comment]
For the desktop version I still see a standard scrollbar (scroll down for other example):
grafik
Should be changed to something similar to the scrollbar when switching to a mobile view:
grafik

**Comment by mariahosfeld** [comment]
Now functionality also works in firefox.

**Review by norbertschuler — APPROVED** [review]
LGFM (MacOS/Chrome): Bildschirmfoto 2022-09-25 um 11 19 13

**Comment by mariahosfeld** [comment]
Wording change also looks good to me.

**Review by mariahosfeld — APPROVED** [review]

**Pull request merged**
