### PR TITLE
Release July 4th

### PR DESCRIPTION
**Pull request by mariahosfeld**
Changes in this pull request:
- #299 
- #303 
- #305 
- #306 
- #307 
- #308 
- #312
- #316 
- #318 

@

### CODE REVIEW

**Comment by norbertschuler** [comment]
- [ ] After paying with SOFORT I do not see a Thank-You screen, but the page to choose the payment method again (compare https://github.com/Plant-for-the-Planet-org/planet-donations/pull/299#issuecomment-1166255514).

**Comment by norbertschuler** [comment]
- [ ] There is a small translation but as the frequency "monthly" in the confirmation mail was not translated to German language:
Bildschirmfoto 2022-07-02 um 11 46 55

**Comment by mariahosfeld** [comment]
> * [ ]  After paying with SOFORT I do not see a Thank-You screen, but the page to choose the payment method again (compare [Add null checks #299 (comment)](https://github.com/Plant-for-the-Planet-org/planet-donations/pull/299#issuecomment-1166255514)). Link to donation: https://app-staging.plant-for-the-planet.org/backend/donationContribution/608988/show

I checked, I was not able to replicate this issue.

**Comment by mohitb35** [comment]
- [ ] After paying with planetcash, I see a client side exception. The console shows:

`TypeError: Cannot read properties of undefined (reading 'country')
    at h (ImageComponent.tsx:62:59)`

Screenshot 2022-07-05 at 11 10 18 AM

**Review by Shreyaschorge — APPROVED** [review]

**Pull request merged**
