### PR TITLE
Disable unsupported payment currencies

### PR DESCRIPTION
**Pull request by mohitb35**
1. Fixes https://github.com/Plant-for-the-Planet-org/planet-webapp/issues/773
2. Fetches supported currencies by API (~~Note - API will be replaced by a new API with a similar response format, to be updated once the API is available~~) and filters list of currencies available while making a donation (in the donate step), removing unsupported currencies from the currency selector.
3. Adds fallback to Euros if an invalid currency is somehow selected (e.g. if you provide ?country=AQ in the URL).  
4. Also includes some code cleanup.

### CODE REVIEW

**Review by norbertschuler — COMMENTED** [review]
I tested what happens if the donate application is called from planet-webapp with an unsupported country (which you still can choose there), e.g. with country code "AQ" https://donate-with-planet-eo8vv1j51-planetapp.vercel.app/?to=ffl-platbos-forest&callback_url=https%3A%2F%2Fplanet-webapp-fvofu7l2h-planetapp.vercel.app%2F&country=AQ&tenant=ten_NxJq55pm&locale=de - it seem to fallback to the formerly chosen currency which is ok for me.

But I still found at least one currency which does not seem to correctly work ("usaf") - maybe we just want to remove it from the list of country in `src/Utils/countriesData.json`?
Bildschirm­foto 2022-11-12 um 12 20 29

**Comment by mohitb35** [comment]
> https://donate-with-planet-eo8vv1j51-planetapp.vercel.app/?to=ffl-platbos-forest&callback_url=https%3A%2F%2Fplanet-webapp-fvofu7l2h-planetapp.vercel.app%2F&country=AQ&tenant=ten_NxJq55pm&locale=de

1. I'll remove "usaf" as an option. 
2. I see that it falls back if there was a previously selected country, but if it's the first visit to donate.planet we still see the old behaviour - i.e. the screen appears to be in loading state. I'll look into the fall back logic and add in a default currency/country fallback as well.

**Comment by mohitb35** [comment]
> > https://donate-with-planet-eo8vv1j51-planetapp.vercel.app/?to=ffl-platbos-forest&callback_url=https%3A%2F%2Fplanet-webapp-fvofu7l2h-planetapp.vercel.app%2F&country=AQ&tenant=ten_NxJq55pm&locale=de
> 
> * [x]   1. I'll remove "usaf" as an option and cross check that no other non-working option exists.
> * [x]  2. I see that it falls back if there was a previously selected country, but if it's the first visit to donate.planet we still see the old behaviour - i.e. the screen appears to be in loading state. I'll look into the fall back logic and add in a default currency/country fallback as well.

@norbertschuler I've updated the PR to remove "usaf" and provide Euros as the fallback currency if it is invalid. The fallback is handled generally, not just if the non supported currency's country code is provided in the URL - so if an invalid currency was set via any means (user profile, config API, from local storage, or provided through `country` in the URL) it will fallback gracefully.

**Review by norbertschuler — APPROVED** [review]
LGFM

**Pull request merged**
