### PR TITLE
Allow user to topup planetcash with queryToken

### PR DESCRIPTION
**Pull request by Shreyaschorge**
Fixes #

- Allow user to topup planetcash with queryToken

### CODE REVIEW

**Comment by norbertschuler** [comment]
Please test this with a query token and link as generated by https://github.com/Plant-for-the-Planet-org/treecounter-app

**Comment by norbertschuler** [comment]
> Please test this with a query token and link as generated by https://github.com/Plant-for-the-Planet-org/treecounter-app

I made a test with https://donate-with-planet-8bx6uqp6g-planetapp.vercel.app/?to=donana-restoration-project-phase-i&s=&locale=de&country=de&token=*** (my secret token from the Treecounter-app) which showed with this screen and changed the URL instantly to https://donate-with-planet-8bx6uqp6g-planetapp.vercel.app/?to=donana-restoration-project-phase-i&locale=de&s=&country=de without the queryToken included:

Bildschirmfoto 2022-08-11 um 13 54 18

Unfortunately trying to pay with PlanetCash directly from this screen does not seem to work. I get stuck with this screen:

Bildschirmfoto 2022-08-11 um 13 57 55

I wonder if maybe the token got lost?

**Comment by Shreyaschorge** [comment]
> > Please test this with a query token and link as generated by https://github.com/Plant-for-the-Planet-org/treecounter-app
> 
> I made a test with https://donate-with-planet-8bx6uqp6g-planetapp.vercel.app/?to=donana-restoration-project-phase-i&s=&locale=de&country=de&token=*** (my secret token from the Treecounter-app) which showed me this screen and changed the URL instantly to https://donate-with-planet-8bx6uqp6g-planetapp.vercel.app/?to=donana-restoration-project-phase-i&locale=de&s=&country=de without the token included:
> 
> Bildschirmfoto 2022-08-11 um 13 54 18
> 
> Unfortunately trying to pay with PlanetCash directly from this screen does not seem to work. I get stuck with this screen:
> 
> Bildschirmfoto 2022-08-11 um 13 57 55
> 
> I wonder if maybe the token got lost?

@norbertschuler It fixed now.

**Review by mohitb35 — COMMENTED** [review]
@Shreyaschorge 

There seem to be some issues if 
1. the token is invalid, or 
2. belongs to an account without an active planetcash account.

In both cases the user gets stuck on a blank screen. In case 1, the `/profile` API response is `500 Internal server error`, and the app gets stuck after a few calls to the API.
Screenshot 2022-08-18 at 4 19 47 PM

In case 2, the `/profile` API response contains `planetCash = null` and the API keeps getting called infinitely.

Screenshot 2022-08-18 at 4 20 38 PM

**Review by mohitb35 — APPROVED** [review]
Looks good to me

**Comment by mohitb35** [comment]
This is resolved.

> @Shreyaschorge
> 
> https://donate-with-planet-c06exw2cv-planetapp.vercel.app/?to=planetcash&token=jknsdkfcjsnk
> 
> There seem to be some issues if
> 
> 1. the token is invalid, or
> 2. belongs to an account without an active planetcash account.
> 
> **https://donate-with-planet-c06exw2cv-planetapp.vercel.app/?to=planetcash&token=InvalidToken** In both cases the user gets stuck on a blank screen. In case 1, the `/profile` API response is `500 Internal server error`, and the app gets stuck after a few calls to the API. Screenshot 2022-08-18 at 4 19 47 PM
> 
> **https://donate-with-planet-c06exw2cv-planetapp.vercel.app/?to=planetcash&token=ValidTokenWithInactivePlanetCashAccount** In case 2, the `/profile` API response contains `planetCash = null` and the API keeps getting called infinitely.
> 
> Screenshot 2022-08-18 at 4 20 38 PM

**Pull request merged**
