### PR TITLE
Add null checks

### PR DESCRIPTION
**Pull request by Shreyaschorge**
Fixes #
- Page break after Success planetCash top-up using Sofort

### CODE REVIEW

**Comment by tejassonar** [comment]
Screenshot 2022-06-03 at 9 52 21 PM

I'm not sure if this issue is related to this PR. But this is worth looking into.
On the top-up screen, I'm seeing donate with planet-cash Button.

**Comment by tejassonar** [comment]
Screenshot 2022-06-03 at 10 04 36 PM
Content and image are missing.

**Comment by norbertschuler** [comment]
> Content and image are missing.

I cannot reproduce this with my PlanetCash account on staging. Can you give more details on what you did (which project you visited and with steps you did)?

**Comment by norbertschuler** [comment]
I can reproduce the fact the left side is empty when topping up you PlanetCash account with Sofort:

Bildschirmfoto 2022-06-04 um 12 09 55

**Review by norbertschuler — CHANGES_REQUESTED** [review]
Crash gets prevented, but site looks ugly.

**Comment by norbertschuler** [comment]
- [ ] I see the following screen instead of a Thank-You screen now after returning from Sofort (having authorized the donation) with the URL https://donate-with-planet-d2zrfno9x-planetapp.vercel.app/?context=don_1uM0vnAbFX7dUOIqd9Wc2SLv&country=DE&locale=en&method=Sofort&payment_intent=pi_3LEWUpD2OpW2f42N04bX6z2m&payment_intent_client_secret=pi_3LEWUpD2OpW2f42N04bX6z2m_secret_Nfnp4rCObKIIWuXQKmRI9mCtK&redirect_status=pending&tenant=ten_I9TW3ncG

Bildschirmfoto 2022-06-25 um 12 46 21

When you click again on above URL, you see following which I would have exspected instead of the above - also there should run some Javascript-Loop checking for updates of the donation until it has succeeded and then showing the Thank-You screen in the end:

Bildschirmfoto 2022-06-25 um 12 48 08

**Review by norbertschuler — COMMENTED** [review]
My quick functional UI test succeeded now in all cases but the first time I tried. I assume for this MR basic donation tests should be done to be sure no other donation processes are broken by this change.

**Comment by mohitb35** [comment]
@Shreyaschorge I noticed that the `/app/donations/:donationId` request is being called many times after making a donation to planet cash. Why would this happen? 

Repeated request: `https://app-staging.plant-for-the-planet.org/app/donations/don_0BFkk9hPVr13tU1MEBsrlgx9?tenant=ten_I9TW3ncG&locale=en`

Screenshot 2022-06-27 at 11 21 07 AM
Screenshot 2022-06-27 at 11 21 07 AM (2)

**Comment by Shreyaschorge** [comment]
> @Shreyaschorge I noticed that the `/app/donations/:donationId` request is being called many times after making a donation to planet cash. Why would this happen?
> 
> Repeated request: `https://app-staging.plant-for-the-planet.org/app/donations/don_0BFkk9hPVr13tU1MEBsrlgx9?tenant=ten_I9TW3ncG&locale=en`
> 
> Screenshot 2022-06-27 at 11 21 07 AM

It will be called untill paymentStatus is the response changes from "pending" to "paid"

**Review by mohitb35 — APPROVED** [review]
@shreyas Looks good to me

I've tried out donating to planet cash via sofort/giropay and this works.
Donation via card/bank transfer to planet cash also work.
Donations via card to regular projects also work.

**Comment by mariahosfeld** [comment]
Tested the functionality, works for me.

**Pull request merged**
