### PR TITLE
Allow User to Top-up PlanetCash only if they are authenticated

### PR DESCRIPTION
**Pull request by Shreyaschorge**
Allow User to Top-up PlanetCash only if they are authenticated

### CODE REVIEW

**Review by tejassonar — APPROVED** [review]

**Comment by norbertschuler** [comment]
- [ ] When I visit a project, then login with my Google account and click on "add balance" I get an exception:
```
TypeError: Cannot read properties of undefined (reading 'quantity')
    at FundingDonations.tsx:77:63
```
E.g. https://donate-with-planet-3k0exe9vh-planetapp.vercel.app/?to=eden-reforestation-projects-madagascar&step=donate -> click link "Add balance" -> https://donate-with-planet-3k0exe9vh-planetapp.vercel.app/?to=pcash_MkU495zTcz6nxr12m0C4pyMt&step=donate -> Exception

Bildschirmfoto 2022-05-18 um 08 30 57

**Comment by norbertschuler** [comment]
> * When I visit a project, then login with my Google account and click on "add balance" I get an exception:

This got already fixed in the develop branch and vanished as I merged develop into this PR.

**Comment by norbertschuler** [comment]
- [ ] This still allowed me to login with a different account and try to add some balance to another account if I remember the right link of the Planet-Cash account, e.g. https://donate-with-planet-4ip4gumzw-planetapp.vercel.app/?to=pcash_MkU495zTcz6nxr12m0C4pyMt&step=donate - as the other account I logged in with had no Planet-Cash account I got a 401 error at the end of the payment process by the API as following:

Request:

```
curl 'https://app-staging.plant-for-the-planet.org/app/donations?tenant=ten_I9TW3ncG&locale=en' \
  -H 'authority: app-staging.plant-for-the-planet.org' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'authorization: Bearer ***' \
  -H 'content-type: application/json' \
  -H 'dnt: 1' \
  -H 'origin: https://donate-with-planet-4ip4gumzw-planetapp.vercel.app' \
  -H 'referer: https://donate-with-planet-4ip4gumzw-planetapp.vercel.app/' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="101", "Google Chrome";v="101"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36' \
  -H 'x-accept-version: 1.2' \
  -H 'x-session-id: 3efc2640-d676-11ec-a23f-77532a7f73c3' \
  --data-raw '{"purpose":"planet-cash","amount":100,"currency":"EUR","donor":{"firstname":"Norbert","lastname":"Schuler","email":"norbert.schuler+tpo@googlemail.com","address":"Stree 1","city":"Hamburg","zipCode":"22765","country":"DE"},"frequency":"once","metadata":{"callback_url":"","callback_method":""},"taxDeductionCountry":"DE"}' \
  --compressed
```

Response:

`"You do not have a planet-cash account set up yet."`

**Review by norbertschuler — CHANGES_REQUESTED** [review]
Allow only the owner of a Planet-Cash account to add balance.

**Comment by norbertschuler** [comment]
- [ ] There is a kind of redirection loop now if you try to call the url of adding balance to a Planet-Cash account you do not belong to after you visited a project, e.g. at https://donate-with-planet-29wsxb5ow-planetapp.vercel.app/?to=one-million-trees-2020&step=donate replace the url with https://donate-with-planet-29wsxb5ow-planetapp.vercel.app/?to=pcash_MkU495zTcz6nxr12m0C4pyMt&step=donate (but not being logged in with my user account):

https://user-images.githubusercontent.com/1532418/169465848-bcf8e2a9-558b-4e20-a907-e44104bb0a79.mov

**Comment by sagararyal** [comment]
@Shreyaschorge Lets solve this properly by changing the planetcash topup link to

/?to=planetCash

this should redirect user to login, and once loggedin, 
get planetCash account of user from /profile


This way, a user can never access someone else's planetCash Account.

**Comment by Shreyaschorge** [comment]
> 

@norbertschuler Not able to recreate this scenario.

**Comment by norbertschuler** [comment]
> > * [ ]   There is a kind of redirection loop now if you try to call the url of adding balance to a Planet-Cash account you do not belong to after you visited a project, e.g. at https://donate-with-planet-29wsxb5ow-planetapp.vercel.app/?to=one-million-trees-2020&step=donate replace the url with https://donate-with-planet-29wsxb5ow-planetapp.vercel.app/?to=pcash_MkU495zTcz6nxr12m0C4pyMt&step=donate (but not being logged in with my user account):
> > 
> > Bildschirmaufnahme.2022-05-20.um.08.22.07.mov
> 
> @norbertschuler Not able to recreate this scenario.

1. Login with a user having a PlanetCash account and open the screen to add some balance.
2. Logout
3. Login with another user not having a PlanetCash account
4. Copy & paste the link to add balance to the first account, e.g. https://donate-with-planet-29wsxb5ow-planetapp.vercel.app/?to=pcash_MkU495zTcz6nxr12m0C4pyMt&step=donate
5. If you get redirect to the default screen to find projects, click on one project
6. If no redirect loop happens yet, copy and paste again the link to add some balance, e.g. https://donate-with-planet-29wsxb5ow-planetapp.vercel.app/?to=pcash_MkU495zTcz6nxr12m0C4pyMt&step=donate into your browser to see the redirect loop starting of.

I admit this maybe is an edge case, but I can reproduce it and I am not sure if it is an indicator for some broken logic in the code.

**Comment by Shreyaschorge** [comment]
> > > * [ ]    There is a kind of redirection loop now if you try to call the url of adding balance to a Planet-Cash account you do not belong to after you visited a project, e.g. at https://donate-with-planet-29wsxb5ow-planetapp.vercel.app/?to=one-million-trees-2020&step=donate replace the url with https://donate-with-planet-29wsxb5ow-planetapp.vercel.app/?to=pcash_MkU495zTcz6nxr12m0C4pyMt&step=donate (but not being logged in with my user account):
> > > 
> > > Bildschirmaufnahme.2022-05-20.um.08.22.07.mov
> > 
> > 
> > @norbertschuler Not able to recreate this scenario.
> 
> 1. Login with a user having a PlanetCash account and open the screen to add some balance.
> 2. Logout
> 3. Login with another user not having a PlanetCash account
> 4. Copy & paste the link to add balance to the first account, e.g. https://donate-with-planet-29wsxb5ow-planetapp.vercel.app/?to=pcash_MkU495zTcz6nxr12m0C4pyMt&step=donate
> 5. If you get redirect to the default screen to find projects, click on one project
> 6. If no redirect loop happens yet, copy and paste again the link to add some balance, e.g. https://donate-with-planet-29wsxb5ow-planetapp.vercel.app/?to=pcash_MkU495zTcz6nxr12m0C4pyMt&step=donate into your browser to see the redirect loop starting of.
> 
> I admit this maybe is an edge case, but I can reproduce it and I am not sure if it is an indicator for some broken logic in the code.

@norbertschuler I followed these steps still could not reproduce the bug.

@tejassonar Can you please try this on your end?

**Comment by tejassonar** [comment]
> > > * [ ]    There is a kind of redirection loop now if you try to call the url of adding balance to a Planet-Cash account you do not belong to after you visited a project, e.g. at https://donate-with-planet-29wsxb5ow-planetapp.vercel.app/?to=one-million-trees-2020&step=donate replace the url with https://donate-with-planet-29wsxb5ow-planetapp.vercel.app/?to=pcash_MkU495zTcz6nxr12m0C4pyMt&step=donate (but not being logged in with my user account):
> > > 
> > > Bildschirmaufnahme.2022-05-20.um.08.22.07.mov
> > 
> > 
> > @norbertschuler Not able to recreate this scenario.
> 
> 1. Login with a user having a PlanetCash account and open the screen to add some balance.
> 2. Logout
> 3. Login with another user not having a PlanetCash account
> 4. Copy & paste the link to add balance to the first account, e.g. https://donate-with-planet-29wsxb5ow-planetapp.vercel.app/?to=pcash_MkU495zTcz6nxr12m0C4pyMt&step=donate
> 5. If you get redirect to the default screen to find projects, click on one project
> 6. If no redirect loop happens yet, copy and paste again the link to add some balance, e.g. https://donate-with-planet-29wsxb5ow-planetapp.vercel.app/?to=pcash_MkU495zTcz6nxr12m0C4pyMt&step=donate into your browser to see the redirect loop starting of.
> 
> I admit this maybe is an edge case, but I can reproduce it and I am not sure if it is an indicator for some broken logic in the code.

@norbertschuler @Shreyaschorge I tried to reproduce this bug, and I found out that this issue is only on Safari and not on the Chrome browser.

**Comment by tejassonar** [comment]
The looping issue is still there.

**Comment by Shreyaschorge** [comment]
Closing in favour of #307

**Pull request closed without merging**
