### PR TITLE
Embeddable donations

### PR DESCRIPTION
**Pull request by sarveshpro**

### CODE REVIEW

**Comment by norbertschuler** [comment]
- [ ] German translation breaks layout on small devices (Italian is even longer!)
- [ ] "cancel" is not the right term any more on the Thank-You screen:

Bildschirmfoto 2021-12-28 um 13 17 27Bildschirmfoto 2021-12-28 um 13 18 07

**Review by norbertschuler — CHANGES_REQUESTED** [review]
Please remove `console.log` before merging and also please let us not include unrelated package upgrades with `package-lock.json` within this PR (or are they necessary for this PR to work?) but do these upgrades in an extra pull request.

**Comment by sagararyal** [comment]
@tejassonar will resolve conflicts, and we test this by end of the week.

**Comment by norbertschuler** [comment]
Part of this already seems to be on production. So what is this PR about? Will it be continued or abandoned?

**Comment by mariahosfeld** [comment]
Closing this.

**Pull request closed without merging**
