### PR TITLE
PlanetCash Release

### PR DESCRIPTION
**Pull request by sagararyal**

### CODE REVIEW

**Comment by Plant-for-the-Planet** [comment]
Cypress Test should be changed to support a new bouquet project: 

Current proj_6x3GTD5cMRv0OeQAiIlJZ0Au has been disabled for donations.

**Comment by norbertschuler** [comment]
- [ ] Adding some balance (topping up) the own PlanetCash account using BankTransfer as payment method is still crashing the backend with an 500 error:

`"Argument 2 passed to App\\Service\\PurposeSubjectCalculator::getAmountForQuantity() must be of the type float, null given, called in /app/src/Common/Payment/PaymentProvider/OfflineProvider.php on line 66\nfile: /app/src/Service/PurposeSubjectCalculator.php, line: 78"`

Bildschirmfoto 2022-04-23 um 11 42 30

**Comment by norbertschuler** [comment]
- [ ] I added some cash to my PlanetCash account. The confirmation says I am getting some email confirmation, but I do not see some mail to be send by the staging backend in the Admin UI. 

Bildschirmfoto 2022-04-23 um 11 45 12

I do not find any information about an email being sent to norbert.schuler@googlemail.com on https://app-staging.plant-for-the-planet.org/backend/emailLog and also not for https://app-staging.plant-for-the-planet.org/backend/donationContribution/597300/show:

Bildschirmfoto 2022-03-27 um 11 01 43

**Comment by norbertschuler** [comment]
- [ ] I just tested donations with the Treecounter-App and the specific url to open a project for some language, country and even transfering the user token to be logged in, does not work any more: http://paydev.pp.eco/?to=donana-restoration-project-phase-i&s=&locale=en&country=de&token=*** - you get redirect to the list of projects instead :-(

**Pull request merged**
