### PR TITLE
Fix TS Warnings

### PR DESCRIPTION
**Pull request by mohitb35**
General code clean up to address TS warnings/errors and other issues highlighted by codefactor.io and the VS Code problems pane.

This includes
- updating types of variables, function params and return types (avoid using `any`, `Object / {}`, `Function`, `unknown` types where possible)
- Adding type guards, type assertions etc, and creating common types/interfaces for use.
- importing and using 3rd party types while using a library (e.g. Paypal/ Stripe)
- removing unused code / commented code / extra comments
- minor refactors to remove extra code / reduce code / address incorrect logic
- initializing component props if needed, and providing missing props while using components
- rename variables/components to indicate purpose better
- removing non null assertions and replacing with optional chaining
- adding comments to indicate future Todos

Closes #309

### CODE REVIEW

**Comment by norbertschuler** [comment]
Make sure this MR does not conflict with https://github.com/Plant-for-the-Planet-org/planet-donations/pull/309.

**Comment by mohitb35** [comment]
Keeping #309 as a reference and making the changes over here.

Regards
Mohit
________________________________

**Review by norbertschuler — COMMENTED** [review]
These are too much changes as I could review them. I assume we just need to check the general functionality of the application before merging this MR.

**Review by Shreyaschorge — COMMENTED** [review]
Codewise. Looks good to me.

**Review by Shreyaschorge — APPROVED** [review]

**Review by norbertschuler — APPROVED** [review]
This MR is too big for me to review without doing a test of the application. We should test as much of the functionality as possible for the release containing this.

**Comment by mariahosfeld** [comment]
Functionality testing looks good to me.

**Pull request merged**
