### PR TITLE
fixed currency change issue on logging in

### LINKED ISSUE #158: Currency changes after login
**Describe the bug**
Currency changes after login.

**Is it on a Production or Development Build?**
All Builds

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to donate page without login (Your country should be other than DE to reproduce this error) 
2. You'll see the currency as INR (for country IN)
3. Now Log in
4. You'll see the currency as Euros
5. After refreshing the currency will again be INR

**Expected behaviour**
Currency should not change

**What actually happens**
Server-side props setting Country as DE by default, which in turn changes currency.

**Screenshots**
Check amount in the following screenshots.
image
image

### PR DESCRIPTION
**Pull request by tejassonar**
Fixed #158 

@sagararyal 
@norbertschuler

### CODE REVIEW

**Review by sagararyal — DISMISSED** [review]
@tejassonar 

When user logs in:
1. the currency from profile gets the highest priority

if there is no currency in the profile,
2. get the currency from localstorage/config

if that can't be retrieved,
3. fall back to default currency.

**Comment by sagararyal** [comment]
The PR is still not respecting the predefined currency

step 1. I set currency to INR
step 2. Login with account without currency --> App sets currency as EUR

Alternate

step 1: I set currency to INR
step 2. login with account with SEK as profile currency --> App sets currency as EUR, and once profile is fetched sets SEK


Expected outcome: Apps should honor the currency user selected before logging in.

**Comment by sarveshpro** [comment]
@tejassonar set priority as localstorage > user profile > middleware/config api > default(EUR)

**Comment by norbertschuler** [comment]
> @tejassonar set priority as **localstorage > user profile > middleware/config api > default(EUR)**

It's working as @tejassonar wrote above, but I understand @sagararyal request as following

```
user profile > localstorage > middleware/config api > default(EUR)
    ^------<-->-----^
```
So what's the correct priority implementation now?

**Comment by sarveshpro** [comment]
> Expected outcome: Apps should honor the currency user selected before logging in.

According to this comment by @sagararyal  `"currency selected by user"(local storage)` > `"before logging in"(user profile)` is the correct implementation.

**Comment by sagararyal** [comment]
@sarveshpro for this, currency shouldn't be added on locale storage unless user overrides. 
Maybe time to finally retire config API in favor of native geo data support using vercel.

**Comment by sagararyal** [comment]
Is using the country from the profile, and not currency. This is fine as currency is determined using paymentOptions API by passing the country.

**Review by ankitecd — APPROVED** [review]
Looks good to me

**Comment by tejassonar** [comment]
> Is using the country from the profile, and not currency. This is fine as currency is determined using paymentOptions API by passing the country.

This PR seems good to me as well.

**Pull request merged**
